# This is a basic workflow to help you get started with Actions

name: lab_recursiveGaussian

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [lab]
  pull_request:
    branches: [lab]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    container:
      image: wukan0621/gpgpu-sim:docker-dependencies-cache

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: build
        run: |
          . $SCC_SETUP_ENV
          test/build_install.sh

      - name: run recursiveGaussian
        run: |
          . $SCC_SETUP_ENV
          export NVCC_PREPEND_FLAGS='--resource-usage -maxrregcount 29 -Xptxas -v -Xptxas -warn-spills -Xptxas -warn-lmem-usage'
          (spack load gcc@7.5.0 cuda &&
              cd test/recursiveGaussian &&
              nvcc --cudart shared -arch=sm_70 -I. -o ~/recursiveGaussian *.cu *.cpp)

          export DATA_PATH=$(realpath --relative-to=$HOME/SM7_QV100 test/recursiveGaussian/data/teapot512.ppm)
          rm -rf ~/SM7_QV100
          cp -r $(spack location -i gpgpu-sim@modified)/gpgpu-sim_distribution/configs/tested-cfgs/SM7_QV100 ~
          spack load gpgpu-sim@modified
          cd $(spack location -i gpgpu-sim@modified)/gpgpu-sim_distribution
          . ./setup_environment release
          cd ~/SM7_QV100
          ~/recursiveGaussian --benchmark --image=$DATA_PATH 2>stderr.log | tee stdout.log

      - uses: actions/upload-artifact@v3
        with:
          path: |
            ~/SM7_QV100/*

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            ~/SM7_QV100/*
